#EXEMPLOS DE VARIAVEIS COM NOMENCLATURAS ERRADAS

"""
# SERVE PARA DEIXAR O CÓDIGO COMENTADO
USAR AS ASPAS DA FORMA QUE ESTOU USANDO PARA DEIXAR ESSE COMENTÁRIO SERVE PARA COMENTAR VARIAS LINHAS, 
PARA NÃO PRECISAR COLOCAR # EM TODAS AS LINHAS
"""

#77nome = "Ricck";

#mai$ = "mais";

#class = "Python";
